apiVersion: v1
kind: Service
metadata:
  name: my-agent
spec:
  selector:
    app: my-agent
  ports:
    - name: proxy
      port: 7701
      targetPort: 7701
    - name: ui
      port: 7700
      targetPort: 7700
